#!/usr/bin/env python3
"""Generate the publisher-neutral manuscript from the IEEE Access source.

The IEEE Access manuscript (paper/src/ieee_access_manuscript.tex) is the single
source of truth. This script rewrites it into a plain single-column article
(11 pt, A4, numbered sections, numeric citations) for submission to journals
other than IEEE Access, so the two versions never drift apart:

  - IEEE front matter (\\history, \\doi, \\address, \\corresp, \\markboth,
    keywords environment, \\maketitle) -> a plain title block, abstract and
    keyword line
  - \\PARstart drop capital -> plain text; figure*/table* -> figure/table;
    "TABLE~\\ref" -> "Table~\\ref"
  - one-column figures (width=\\columnwidth) -> 0.65\\textwidth; tables that were
    stretched to the column are only shrunk if wider than the text
  - author biographies and \\EOD dropped (IEEE-specific)

Text, numbers, tables, figures, equations and references are copied unchanged.

Output: master/src/master_manuscript.tex (build: make -C master)
Usage (repo root): python3 scripts/make_master_manuscript.py
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "paper" / "src" / "ieee_access_manuscript.tex"
OUT = ROOT / "master" / "src" / "master_manuscript.tex"

PREAMBLE = r"""% ======================================================================
% GENERATED by scripts/make_master_manuscript.py from
% paper/src/ieee_access_manuscript.tex -- do not edit; edit the IEEE source
% and re-run the script. Publisher-neutral single-column version.
% ======================================================================
\documentclass[11pt]{article}

\usepackage[a4paper,top=2.5cm,bottom=2.5cm,left=2.5cm,right=2.5cm]{geometry}
\usepackage{amsmath,amssymb,amsfonts}
\usepackage{graphicx}
\usepackage{textcomp}
\usepackage[hyphens]{url}
\usepackage{bm}
\usepackage{amsthm}
\usepackage{float}
\usepackage{booktabs}
\usepackage{array}
\usepackage{rotating}
\usepackage{cite}
\usepackage[font=small,labelfont=bf,labelsep=period]{caption}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[hidelinks]{hyperref}
\urlstyle{same}

\renewcommand{\thetable}{\Roman{table}}
\setlength{\emergencystretch}{3em}
\graphicspath{{../../paper/figures/}}
\makeatletter\newcommand{\tabinput}[1]{\@@input #1 }\makeatother

\theoremstyle{definition}
\newtheorem{definition}{Definition}
\newtheorem{remark}{Remark}
\theoremstyle{plain}
\newtheorem{proposition}{Proposition}

\floatstyle{ruled}
\newfloat{algorithm}{tbp}{loa}
\floatname{algorithm}{Algorithm}
\newcounter{algstep}
\newenvironment{algsteps}{%
  \footnotesize
  \setcounter{algstep}{0}%
  \begin{list}{\textbf{\thealgstep:}}{%
    \usecounter{algstep}%
    \setlength{\labelwidth}{14pt}%
    \setlength{\labelsep}{4pt}%
    \setlength{\leftmargin}{20pt}%
    \setlength{\rightmargin}{0pt}%
    \setlength{\itemsep}{1pt}%
    \setlength{\parsep}{0pt}%
    \setlength{\topsep}{3pt}%
  }%
}{\end{list}}
\newcommand{\algind}[1]{\hspace*{#1.1em}}
\newcommand{\algkw}[1]{\textbf{#1}}
\newcommand{\algcomment}[1]{\textit{$\triangleright$~#1}}
\AtBeginDocument{\renewcommand{\ttdefault}{lmtt}}

\begin{document}
"""


def grab(text: str, start: str, end: str) -> str:
    a = text.index(start) + len(start)
    return text[a:text.index(end, a)]


def authors_block(src: str) -> str:
    raw = grab(src, r"\author{", r"}" + "\n\n" + r"\address")
    names = re.findall(r"\\uppercase\{([^}]*)\}\\authorrefmark\{([^}]*)\}", raw)
    people = [f"{n.replace('S. ', 'S.~')}$^{{{m}}}$" for n, m in names]
    line = ", ".join(people[:-1]) + ", and " + people[-1]
    addrs = re.findall(r"\\address\[(\d)\]\{(.*?)\}\n", src, flags=re.S)
    aff = "\\\\\n".join(f"$^{{{k}}}$" + " ".join(a.split()) + "." for k, a in addrs)
    corr = grab(src, r"\corresp{", "}\n")
    corr = corr.replace("S. Kanaga", "S.~Kanaga")
    return (f"\\begin{{center}}\n{line}\n\\end{{center}}\n\n\\vspace{{0.3em}}\n\\footnotesize\n"
            f"\\noindent{aff}\\\\\n\\vspace{{0.3em}}\n{corr}\n\\normalsize\n\n\\vspace{{1em}}\n")


def body(src: str) -> str:
    b = src[src.index(r"\section{Introduction}"):src.index(r"\begin{IEEEbiographynophoto}")]
    b = b.rstrip() + "\n"
    b = re.sub(r"\\PARstart\{(\w)\}\{(\w+)\}", r"\1\2", b)
    b = b.replace(r"\begin{figure*}", r"\begin{figure}").replace(r"\end{figure*}", r"\end{figure}")
    b = b.replace(r"\begin{table*}", r"\begin{table}").replace(r"\end{table*}", r"\end{table}")
    b = b.replace("[!t]", "[!htbp]")
    b = b.replace("TABLE~", "Table~")
    b = b.replace(r"\includegraphics[width=\columnwidth]", r"\includegraphics[width=0.65\textwidth]")
    b = b.replace(r"\resizebox{\columnwidth}{!}{",
                  r"\resizebox{\ifdim\width>\textwidth\textwidth\else\width\fi}{!}{")
    b = b.replace(r"p{0.66\columnwidth}", r"p{0.6\textwidth}")
    b = b.replace(r"\tabinput{../tables/", r"\tabinput{../../paper/tables/")
    # Tables that spanned both IEEE columns can be wider than this text block:
    # shrink any tabular not already inside a \resizebox, but only if too wide.
    fit = r"\resizebox{\ifdim\width>\textwidth\textwidth\else\width\fi}{!}{"
    parts, pos = [], 0
    for m in re.finditer(r"\\begin\{tabular\}.*?\\end\{tabular\}", b, flags=re.S):
        before = b[max(0, m.start() - 80):m.start()]
        parts.append(b[pos:m.start()])
        parts.append(m.group(0) if "resizebox" in before else fit + m.group(0) + "}")
        pos = m.end()
    b = "".join(parts) + b[pos:]
    # The roster of the earlier evaluation is too wide for a portrait page:
    # set it landscape on its own page.
    m = re.search(r"\\begin\{table\}\[!htbp\](?:(?!\\end\{table\}).)*?tab_runpod_main"
                  r".*?\\end\{table\}", b, flags=re.S)
    if m:
        t = m.group(0).replace(r"\begin{table}[!htbp]", r"\begin{sidewaystable}")
        t = t.replace(r"\end{table}", r"\end{sidewaystable}").replace(r"\scriptsize", r"\footnotesize")
        t = t.replace(r"\resizebox{\ifdim\width>\textwidth\textwidth\else\width\fi}{!}{",
                      r"\resizebox{\ifdim\width>\textheight\textheight\else\width\fi}{!}{")
        t = t.replace(r"p{0.135\textwidth}", r"p{0.2\textheight}")
        assert r"\textheight\textheight" in t, "landscape sizing not applied"
        b = b[:m.start()] + t + b[m.end():]
    return b


def main() -> int:
    src = SRC.read_text()
    title = grab(src, r"\title{", "}\n")
    abstract = grab(src, r"\begin{abstract}", r"\end{abstract}").strip()
    keywords = grab(src, r"\begin{keywords}", r"\end{keywords}").strip()
    out = (PREAMBLE
           + f"\\begin{{center}}\n{{\\Large\\bfseries {title}}}\n\\end{{center}}\n\n"
           + authors_block(src)
           + f"\\begin{{abstract}}\n{abstract}\n\\end{{abstract}}\n\n"
           + f"\\noindent\\textbf{{Keywords:}} {keywords}.\n\n\\vspace{{1em}}\n\n"
           + body(src)
           + "\n\\end{document}\n")
    for bad in (r"\PARstart", r"figure*", r"table*", r"\columnwidth", "IEEEbiography",
                r"\EOD", "TABLE~"):
        assert bad not in out, bad
    OUT.write_text(out)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(out.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
