#!/usr/bin/env python3
"""Generate the manuscript's results tables from committed outputs.

Every number in paper/tables/*.tex is read from results/ CSVs written by
scripts/run_exp04_final.py, run_precision_gate.py and run_pair_gate.py;
nothing is typed by hand. Re-run after any analysis change.

Usage (repo root): python3 scripts/make_exp04_tables.py
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
R = ROOT / "results"
T = ROOT / "paper" / "tables"

NICE = {
    "primary": "Primary", "primary_strict": "Primary, verified roots",
    "primary_S1position": "Primary + S1 (option distribution)",
    "primary_S2acc0.3": "Primary, S2 (acc $\\geq$ 0.30)",
    "primary_S1position_S2acc0.3": "Primary + S1, S2",
    "primary_strict_S1position_S2acc0.3": "Primary, verified + S1, S2",
    "expanded": "Expanded", "expanded_strict": "Expanded, verified roots",
    "expanded_S1position": "Expanded + S1 (option distribution)",
    "expanded_S2acc0.3": "Expanded, S2 (acc $\\geq$ 0.30)",
    "expanded_S1position_S2acc0.3": "Expanded + S1, S2",
    "expanded_strict_S1position_S2acc0.3": "Expanded, verified + S1, S2",
}


DAGGER = "$^\\dagger$"
GEQ = "$\\geq$"


def fmt_ci(e, lo, hi, d=3):
    return f"${e:+.{d}f}$ [{lo:+.{d}f}, {hi:+.{d}f}]"


def pval(p):
    return "$<$0.001" if p < 0.001 else f"{p:.3f}"


def write(name: str, body: str) -> None:
    T.mkdir(parents=True, exist_ok=True)
    (T / name).write_text("% generated by scripts/make_exp04_tables.py -- do not edit\n"
                          + body)


def tab_prereg():
    d = pd.read_csv(R / "exp04_final/prereg_12.csv")
    order = list(NICE)
    lines = []
    for a in order:
        s = d[(d.analysis == a) & (d.term == "same_root")].iloc[0]
        g = d[(d.analysis == a) & (d.term == "gap0")].iloc[0]
        lines.append(f"{NICE[a]} & {int(s.models)} & {int(s.pairs):,} & "
                     f"{fmt_ci(s.estimate, s.ci_low, s.ci_high)} & "
                     f"{fmt_ci(g.estimate, g.ci_low, g.ci_high, 4)} & {pval(g.p)} \\\\")
        if a == "primary_strict_S1position_S2acc0.3":
            lines.append("\\hline")
    write("tab_prereg.tex", "\n".join(lines) + "\n")


def tab_inference():
    d = pd.read_csv(R / "exp04_final/inference_audit.csv")
    lines = []
    for (pop, term), g in d.groupby(["population", "term"], sort=False):
        for r in g.itertuples():
            label = r.inference.replace(" (pre-registered)", DAGGER)
            who = "same root" if term == "same_root" else "same month"
            dig = 3 if term == "same_root" else 4
            lines.append(f"{pop.replace('_S2', ', S2')} & {who} & {label} & "
                         f"{fmt_ci(r.estimate, r.ci_low, r.ci_high, dig)} & {pval(r.p)} \\\\")
        lines.append("\\hline")
    write("tab_inference.tex", "\n".join(lines[:-1]) + "\n")


def tab_outcome():
    d = pd.read_csv(R / "exp04_final/outcome_audit.csv")
    lines = []
    for pop, g in d.groupby("population", sort=False):
        for v, h in g.groupby("variant", sort=False):
            s = h[h.term == "same_root"].iloc[0]
            m = h[h.term == "gap0"].iloc[0]
            vlab = (v.replace(">=", GEQ)
                    .replace("position-based chance", "option-distribution chance"))
            lines.append(f"{pop.capitalize()} & {vlab} & "
                         f"{fmt_ci(s.estimate, s.ci_low, s.ci_high)} & "
                         f"{fmt_ci(m.estimate, m.ci_low, m.ci_high, 4)} & {pval(m.p)} \\\\")
        lines.append("\\hline")
    write("tab_outcome.tex", "\n".join(lines[:-1]) + "\n")


def tab_flow():
    f = pd.read_csv(R / "exp04_final/model_flow.csv")
    e = pd.read_csv(R / "exp04_final/sample_exclusions.csv", index_col=0)
    v = lambda x: "--" if pd.isna(x) else f"{int(x):,}"  # noqa: E731
    lines = [f"{r.stage} & {v(r.primary)} & {v(r.expanded)} \\\\" for r in f.itertuples()]
    lines.insert(4, "\\hline")
    lines.append("\\hline")
    names = {"no_complete_run": "excluded: no complete MMLU run",
             "repo_missing": "excluded: details repository missing",
             "schema_error": "excluded: unreadable predictions"}
    for k, lab in names.items():
        lines.append(f"\\quad {lab} & {int(e.loc[k, 'primary'])} & "
                     f"{int(e.loc[k, 'expanded'])} \\\\")
    write("tab_flow.tex", "\n".join(lines) + "\n")


def tab_precision():
    s = pd.read_csv(R / "precision_gate/summary.csv")
    keep = {"obs16": "16 evaluated models", "sel22": "22-model selection",
            "cand47": "47-model candidate frame",
            "sweep_F6_E8_M5": "30-model ``sufficient'' design",
            "sweep_F7_E8_M6": "42-model sweep design",
            "nested72": "nested reference (72)"}
    lines = []
    for k, lab in keep.items():
        r = s[s.design == k].iloc[0]
        rmse = "not identified" if pd.isna(r.worst_share_rmse_mc) else f"{r.worst_share_rmse_mc:.3f}"
        kap = ("singular" if r.fe_kappa_max_over_ref == float("inf")
               else f"{r.fe_kappa_min_over_ref:.0f}--{r.fe_kappa_max_over_ref:.0f}")
        lines.append(f"{lab} & {int(r.families)} & {int(r.eras)} & "
                     f"{'yes' if r.fe_rank_ok else 'no'} & {kap} & {int(r.basis_rank)}/3 & {rmse} \\\\")
    write("tab_precision.tex", "\n".join(lines) + "\n")


def tab_pairgate():
    lines = []
    for cap in (15, 40, 1000):
        d = pd.read_csv(R / f"pair_gate/primary/power_full_cap{cap}.csv",
                        keep_default_na=False).set_index("truth")
        null = max(d.loc["null", "same_root_reject5"], d.loc["null", "gap0_reject5"],
                   d.loc["null", "gap1_2_reject5"])
        leak = max(d.loc[[t for t in d.index if t.startswith("lineage")], "gap0_reject5"].max(),
                   d.loc[[t for t in d.index if t.startswith("lineage")], "gap1_2_reject5"].max(),
                   d.loc[[t for t in d.index if t.startswith("era")], "same_root_reject5"].max())
        lines.append(f"{'none' if cap == 1000 else cap} & {int(d.N.iloc[0])} & "
                     f"{100 * null:.0f}\\% & {100 * leak:.0f}\\% & "
                     f"{100 * d.loc['lineage_0.05', 'same_root_reject5']:.0f}\\% / "
                     f"{100 * d.loc['era_0.05', 'gap0_reject5']:.0f}\\% & "
                     f"{100 * d.loc['lineage_0.03', 'same_root_reject5']:.0f}\\% / "
                     f"{100 * d.loc['era_0.03', 'gap0_reject5']:.0f}\\% \\\\")
    write("tab_pairgate.tex", "\n".join(lines) + "\n")


def tab_exploratory():
    d = pd.read_csv(R / "exp04_final/exploratory_E1_E2.csv")
    lines = []
    for _, r in d.iterrows():
        pop = r["population"].capitalize().replace("_s2", ", S2")
        lines.append(f"{pop} & {r['models']} & {r['same_root (root-cl)']} & "
                     f"{r['same_root +size/arch']} & {r['gap0 +size/arch']} & "
                     f"{r['same_arch']} \\\\")
    write("tab_exploratory.tex", "\n".join(lines) + "\n")


def jk(r, d):
    """Estimate with a 95% CI from the delete-one-root jackknife SE."""
    return fmt_ci(r.estimate, r.estimate - 1.96 * r.se_jackknife,
                  r.estimate + 1.96 * r.se_jackknife, d)


def tab_itemnull():
    d = pd.read_csv(R / "exp04_item_null/item_null.csv")
    short = {"pre-registered: same-wrong agreement": "Same-wrong agreement (primary outcome)",
             "N1a: minus item distractor null (all models)": "N1a: minus item distractor null",
             "N1b: minus item distractor null (roots weighted equally)": "N1b: as N1a, roots weighted equally",
             "N2: excess co-failure over Rasch null (per item)": "N2: co-failure over Rasch null (per item)"}
    lines = []
    for pop, g in d.groupby("population", sort=False):
        for o, h in g.groupby("outcome", sort=False):
            r = h[h.term == "same_root"].iloc[0]
            m = h[h.term == "gap0"].iloc[0]
            lines.append(f"{pop.replace('_S2', ', S2').capitalize()} & {short[o]} & "
                         f"{r.outcome_mean:.3f} & "
                         f"{jk(r, 3)} & {pval(r.p_jackknife)} & "
                         f"{jk(m, 4)} & {pval(m.p_jackknife)} \\\\")
        lines.append("\\hline")
    write("tab_itemnull.tex", "\n".join(lines[:-1]) + "\n")


def tab_gateaudit():
    """Post-hoc 1,000-replicate audit of the pair gate (Wilson 95% CIs)."""
    files = sorted((R / "pair_gate_audit").glob("*_cap*.csv"))
    if not files:
        return
    order = [("primary", 15), ("primary", 40), ("primary", 1000), ("expanded", 40)]
    lines = []
    for pop, cap in order:
        f = R / "pair_gate_audit" / f"{pop}_cap{cap}.csv"
        if not f.exists():
            continue
        d = pd.read_csv(f, keep_default_na=False)

        def cell(rows):
            r = rows.loc[rows.rate.idxmax()]
            return f"{100 * r.rate:.1f} [{100 * r.ci_low:.1f}, {100 * r.ci_high:.1f}]"

        null = d[d.truth == "null"]
        leak = pd.concat([d[d.truth.str.startswith("lineage") & d.term.isin(["gap0", "gap1_2"])],
                          d[d.truth.str.startswith("era") & (d.term == "same_root")]])
        pw = lambda t, term: cell(d[(d.truth == t) & (d.term == term)])  # noqa: E731
        lines.append(f"{pop.capitalize()} & {'none' if cap == 1000 else cap} & {int(d.N.iloc[0])} & "
                     f"{cell(null)} & {cell(leak)} & {pw('lineage_0.05', 'same_root')} & "
                     f"{pw('era_0.05', 'gap0')} & {pw('lineage_0.03', 'same_root')} & "
                     f"{pw('era_0.03', 'gap0')} \\\\")
    write("tab_gateaudit.tex", "\n".join(lines) + "\n")


def tab_rawadj():
    d = pd.read_csv(R / "exp04_final/raw_vs_adjusted.csv")
    lab = {"same_root": "Shared root", "gap0": "Same month", "gap1_2": "1--2 months",
           "gap3_5": "3--5 months", "gap6_11": "6--11 months"}
    lines = []
    for t, name in lab.items():
        cells = []
        for pop in ("primary", "expanded"):
            for model in ("raw (no accuracy terms)", "adjusted (pre-registered)"):
                r = d[(d.population == pop) & (d.model == model) & (d.term == t)].iloc[0]
                cells.append(fmt_ci(r.estimate, r.ci_low, r.ci_high, 3))
        lines.append(f"{name} & " + " & ".join(cells) + " \\\\")
    write("tab_rawadj.tex", "\n".join(lines) + "\n")


if __name__ == "__main__":
    for f in (tab_prereg, tab_inference, tab_outcome, tab_flow, tab_precision,
              tab_pairgate, tab_exploratory, tab_itemnull, tab_gateaudit, tab_rawadj):
        f()
    print(sorted(p.name for p in T.glob("*.tex")))
