#!/usr/bin/env python3
"""Writes audit/CLAIM_EVIDENCE_LEDGER.csv and audit/ISSUE_REGISTER.csv.

Status vocabulary (claim ledger):
  REPRODUCED          recomputed by the audit's independent code (audit/tools) from validated answer files
  VERIFIED            checked by the audit against a source (code, git history, public source, policy page, cited paper)
  COMMITTED ONLY      value matches the committed output file; not independently recomputed in this audit
  AUTHOR STATEMENT    cannot be verified from artifacts
  IMPRECISE           substantively true but worded so that it can mislead
  PARTLY CONTRADICTED statement is not literally true as written
"""
import csv
from pathlib import Path

A = Path(__file__).resolve().parents[1]
H = ["id", "claim", "location", "type", "evidence_required", "supporting_artifact", "directness",
     "verification_status", "discrepancy", "overstated", "action"]
R = lambda *r: r  # noqa: E731

ledger = [
 R("C01", "977 models pass item-level validation, forming two overlapping samples (primary 590, expanded 928)", "Abstract; III-C", "descriptive", "validation manifest + answer files", "results/exp04_validation/per_model.csv; datasets/ollb/frozen_full", "direct", "REPRODUCED", "590/928 count leaderboard ENTRIES: 552 distinct prediction vectors in the primary sample, 563 distinct Hub repositories (50 entries -> 23 repositories)", "minor", "Say 'leaderboard entries' once (ISS-03)"),
 R("C02", "Validation = reconstructed predictions checked against stored item-level correctness on every item", "Abstract; III-A", "methodological", "extraction code; independent re-extraction", "src/lineage_era/ollb/fetch_v1.py; audit/tools/independent_extraction_check.py", "direct", "VERIFIED", "3 models (one per storage layout) re-extracted from the live leaderboard with independent code: 0 mismatches in prediction, correctness, answer key over 42,126 item rows", "no", "-"),
 R("C03", "Acceptance rules (i) 14,042 items, (ii) correctness matches stored flag on every item, (iii) item order and answer key match a reference", "III-A", "methodological", "extraction + analysis gate", "fetch_v1.py; analysis.py; validation_report.py; tests", "direct", "VERIFIED", "Gate enforced since PR #3; manifest does not bind a file to its model (swap reproducer passes the gate); no swap exists in the data (977/977 accuracies match manifest)", "no", "Add content hash or accuracy comparison to the loader (ISS-12)"),
 R("C04", "Spot-checked Llama-2-7b-hf: extracted accuracy equals the leaderboard's official aggregate (43.80)", "III-A", "reproducibility", "stored accuracy of the file", "datasets/ollb/v1/meta-llama__Llama-2-7b-hf.npz", "direct", "IMPRECISE", "Item-level accuracy is 42.76%; 43.80 is the mean over the 57 subjects (macro-average), which is how the leaderboard reports it", "minor", "State both averages (ISS-02)"),
 R("C05", "Three storage layouts among accepted models: 692 / 253 / 32", "III-A", "descriptive", "manifest", "per_model.csv", "direct", "REPRODUCED", "-", "no", "-"),
 R("C06", "6,896 leaderboard models; 721 eligible (primary), 1,295 (expanded); exclusion reasons 4,843/1,637/776/1,209/385/339/56", "III-B", "descriptive", "roster rebuilt from public source", "scripts/fetch_v1_contents_meta.py; roster_v1", "direct", "REPRODUCED", "Rebuilt in a clean clone from the live leaderboard; contents-table SHA-256 identical to 9 Oct", "no", "-"),
 R("C07", "Upload months span 27 months, March 2022 to July 2024", "III-B", "descriptive", "roster", "roster_v1 output", "direct", "REPRODUCED", "-", "no", "-"),
 R("C08", "Samples were frozen with SHA-256 hashes before any prediction was downloaded", "III-C", "methodological", "commit and file times", "git log; mtime of datasets/ollb/v1", "indirect", "PARTLY CONTRADICTED", "Freeze commit 13:15 IST; bulk download from 13:46; but the reference model's answer file (Llama-2-7b-hf) was written at 11:39, before the freeze", "minor", "Reword: 'before the bulk download (the reference model, needed for the answer key, had been fetched earlier)' (ISS-01)"),
 R("C09", "Samples drawn with a fixed seed, at most 40 models per root", "III-C", "reproducibility", "sampling script", "scripts/compare_rosters.py (seed 0, cap 40)", "direct", "REPRODUCED", "Re-running the script in a clean clone reproduces all four recorded SHA-256 hashes; script is not named in the runbook", "no", "Name the script in the runbook (ISS-17)"),
 R("C10", "1,018 models in the samples; 977 validated; 41 excluded and logged, none replaced", "III-C", "descriptive", "manifest", "per_model.csv", "direct", "REPRODUCED", "33 no complete run, 7 repository missing, 1 unreadable", "no", "-"),
 R("C11", "Primary: 590 models, 351 roots (63 with >=2), 173,755 pairs; expanded: 928 models, 422 roots (108), 430,128 pairs", "III-C; Table II", "descriptive", "independent pair construction", "audit/outputs/independent_results.json", "direct", "REPRODUCED", "-", "no", "-"),
 R("C12", "Median accuracy 0.415; 247 primary models below 0.30", "III-C", "descriptive", "answer files", "independent_checks.json", "direct", "REPRODUCED", "-", "no", "-"),
 R("C13", "50 leaderboard entries resolve to 23 repositories; 193 primary pairs agree on >=99.9% of items; 21 models give one letter on >=95% of items", "III-D", "descriptive", "Hub canonical ids; answer files", "hub_meta.jsonl; answer files", "direct", "REPRODUCED", "-", "no", "-"),
 R("C14", "Same-root pairs by gap: 711, 1,004, 259, 45, 1 at 0, 1-2, 3-5, 6-11, 12+ months", "III-E", "descriptive", "independent pair table", "independent_checks.json", "direct", "REPRODUCED", "-", "no", "-"),
 R("C15", "Each pair has between 1,166 and 10,820 jointly wrong items (median 4,109)", "IV-B", "descriptive", "independent pair table", "independent_checks.json", "direct", "REPRODUCED", "-", "no", "-"),
 R("C16", "Outcome a_ij and Eq. 2 specification as written (bins 0,1-2,3-5,6-11 vs 12+; accuracy sum and absolute difference)", "IV-B, IV-C", "methodological", "independent implementation from the equations", "audit/tools/independent_verify.py", "direct", "REPRODUCED", "Independent estimate/SE differ from committed outputs by <=1.2e-9 across all 12 analyses", "no", "-"),
 R("C17", "Dyadic cluster-robust SEs (Eq. 3) and delete-one-root jackknife as described", "IV-E", "statistical", "brute-force and refit checks", "independent_verify.py", "direct", "REPRODUCED", "Eq. 3 formula equals an O(P^2) brute-force sum to 1.9e-16; each jackknife replicate refits the full OLS", "no", "-"),
 R("C18", "The jackknife gives the widest intervals of the three estimators for both coefficients in every sample", "IV-E", "statistical", "inference audit", "results/exp04_final/inference_audit.csv", "direct", "REPRODUCED", "8 of 8 term x sample combinations", "no", "-"),
 R("C19", "Root cluster bootstrap interval 11.4-19.6; jackknife chosen before the bootstrap was run", "IV-E; V-E", "statistical", "bootstrap; commit order", "R10.csv; a008920 vs b8dfa38", "direct", "REPRODUCED", "Independent vertex bootstrap (B=2000, other seed): 11.5-19.0; jackknife appears in a008920 (9 Oct), bootstrap later", "no", "-"),
 R("C20", "Plan, three amendments and first pair outcome committed on 9 Oct 2026 within about 4.5 hours; order recorded only by commit times", "IV-F", "history", "git log", "commits 898c223 ... 679c5b7", "indirect", "VERIFIED", "11:27 -> 15:55 = 4 h 28 min; rewrite of history preserved all author and committer dates (26/26)", "no", "-"),
 R("C21", "An earlier plan paragraph proposed random effects 'an hour before' the fixed OLS specification", "IV-F", "history", "git history of the plan", "898c223 (11:27) vs d84bee5 (12:06)", "direct", "IMPRECISE", "39 minutes", "minor", "'about forty minutes' (ISS-10)"),
 R("C22", "Amendment 3 followed the accuracies of the first 443 validated models", "IV-F", "history", "download log", "fetch_v1_log.jsonl (no timestamps)", "indirect", "AUTHOR STATEMENT", "Order consistent with commit times (downloads from 13:46, amendment 14:44); the count 443 cannot be reconstructed", "no", "-"),
 R("C23", "Plan not registered externally", "Abstract; IV-F", "history", "absence of deposit", "docs; README", "indirect", "VERIFIED", "No registry record found; statement is consistent with repository", "no", "-"),
 R("C24", "Table III statuses (pre-spec., amendment, exploratory, post hoc, planned-run-late, not done)", "Table III", "history", "git history of plan and analyses", "docs/05_Experiments/Exp04*.md; commits", "indirect", "VERIFIED", "Tree distance and phi were in the plan at 12:06; E1/E2 first run with the results (679c5b7); item nulls etc. after review", "no", "-"),
 R("C25", "Simulation check: criteria met except leakage 10.8% (95% CI 8.4-13.8) at lambda_E=0.10; null 5.8-7.8%; power 100%", "IV-G; S3", "statistical", "Monte Carlo outputs", "results/pair_gate*", "direct", "COMMITTED ONLY", "Not re-run (Monte Carlo)", "no", "-"),
 R("C26", "Model-level SEs 3-5% smaller than simulated spread", "IV-G; VII", "statistical", "Monte Carlo outputs", "results/pair_gate_audit", "direct", "COMMITTED ONLY", "-", "no", "-"),
 R("C27", "Raw agreement 71-75% (same root) vs 40-45% (different roots); overall 73.1/42.0, mean 42.3", "V-A", "descriptive", "independent pair table", "independent_checks.json", "direct", "REPRODUCED", "0.731 / 0.420 / 0.423", "no", "-"),
 R("C28", "Kim et al. report the same mean (0.423) on a later HF leaderboard snapshot with mostly ten options", "V-A", "literature", "Kim et al. full text", "arXiv 2506.07962", "direct", "VERIFIED", "Their mean on HuggingFace is 0.423 (12,032 questions)", "no", "-"),
 R("C29", "Primary shared-root coefficient 13.3 points, jackknife 95% CI 10.8-15.8; model-level CI 11.8-14.8", "Abstract; V-B", "statistical", "independent recomputation", "independent_results.json", "direct", "REPRODUCED", "13.293 [10.78, 15.80]; model-level [11.75, 14.84]", "no", "-"),
 R("C30", "Same-month +0.4 points (jackknife CI -0.5 to +1.3)", "V-B", "statistical", "independent recomputation", "independent_results.json", "direct", "REPRODUCED", "0.386 [-0.48, 1.25]", "no", "-"),
 R("C31", "Expanded: 12.7 points (jackknife 11.0-14.5; model-level 11.5-14.0)", "Abstract; V-B", "statistical", "independent recomputation", "independent_results.json", "direct", "REPRODUCED", "12.745 [10.98, 14.51]; [11.48, 14.01]", "no", "-"),
 R("C32", "Shared-root coefficient 11.7-13.4 across the twelve analyses", "V-B", "statistical", "independent recomputation of all 12", "independent_checks.json", "direct", "REPRODUCED", "11.66-13.36", "no", "-"),
 R("C33", "Same-month +1.0 (S1, CI +0.05 to +1.95); -1.5 (S2, model CI -2.7 to -0.2, jackknife -3.0 to +0.1)", "V-B", "statistical", "independent recomputation", "independent_*.json", "direct", "REPRODUCED", "S1 1.00 [0.05, 1.95]; S2 -1.45, jackknife [-3.03, +0.13]", "no", "-"),
 R("C34", "Median accuracy 0.26 (2022-23) vs 0.59 (2024); Spearman 0.41", "V-C", "descriptive", "independent", "independent_checks.json", "direct", "REPRODUCED", "0.264 / 0.587 / 0.409", "no", "-"),
 R("C35", "Without accuracy terms: shared root 28.3; gap coefficients 8.7 (same month) to 2.9 (6-11 months)", "V-C", "statistical", "independent", "independent_checks.json", "direct", "REPRODUCED", "-", "no", "-"),
 R("C36", "With accuracy terms every release-gap coefficient is within 0.6 points of zero in both populations", "V-C; V-D", "statistical", "baseline specification", "prereg_12.csv", "direct", "IMPRECISE", "True for the pre-specified baseline only; S1 gives +1.0 (primary) and +1.4 (expanded) for the same month", "minor", "Add 'in the pre-specified model' (ISS-08)"),
 R("C37", "Root-release-month model: same month -0.1 (-1.2 to +1.0); 12,271 different-root pairs share a root release month; lineage 13.1", "V-D", "statistical", "independent", "hub_meta.jsonl", "direct", "REPRODUCED", "-0.07 [-1.1, +1.0]; 12,271 exactly; 13.1", "no", "-"),
 R("C38", "Joint timing model: same upload month +1.8 (0.3-3.3), same root month -1.5; expanded +0.7/+0.5; S2 +1.3/-3.3", "V-D", "statistical", "R-series", "results/exp04_revision2/revision2.csv", "direct", "COMMITTED ONLY", "-", "no", "-"),
 R("C39", "Equivalence bounds: 1.1 (primary), 1.3 (expanded), 2.0-2.8 (S2)", "V-D", "statistical", "90% jackknife interval", "revision2.csv", "direct", "REPRODUCED", "Primary 90% interval [-0.34, +1.11]; others committed only", "no", "-"),
 R("C40", "'Neither measure alone shows a positive association'", "V-D", "interpretive", "same-month coefficients", "-", "indirect", "IMPRECISE", "Positive in several specifications (S1 +1.0, matched +3.3) per the same paragraph", "minor", "'Neither timing measure alone shows a positive association in the pre-specified model' (ISS-09)"),
 R("C41", "Phi (0.170), CAPA (0.194), option-chance (12.5), WLS (14.2) lineage coefficients", "V-E; Table V", "statistical", "independent", "secondary_outcomes.json", "direct", "REPRODUCED", "0.1698 / 0.1936 / 12.51 / 14.19", "no", "-"),
 R("C42", "N1a: mean outcome falls 0.423 -> 0.002; lineage contrast unchanged (13.3)", "V-E", "statistical", "independent", "secondary_outcomes.json", "direct", "REPRODUCED", "0.0022; 13.31. N1b and Rasch N2 committed only", "no", "-"),
 R("C43", "Pair x item model: lineage 14.2 (10.7-17.6), same month +1.1", "V-E; S6", "statistical", "R9", "R9.csv", "direct", "COMMITTED ONLY", "Identically weighted pair-level fit reproduced (14.19)", "no", "-"),
 R("C44", "Flexible accuracy controls: quadratic 12.3; deciles 12.7; 20 bins 11.9 (8.4-15.3); matched 14.8; range 11.0-14.9", "V-E; S6", "statistical", "R7", "R7.csv", "direct", "COMMITTED ONLY", "Not recomputed independently", "no", "-"),
 R("C45", "Matched pairs: same month +3.3; 74% of matched primary pairs join two near-chance models; stays positive above 0.30 (+3.4) and with S1 (+3.1)", "V-E; S6", "statistical", "R7, R13", "R13.csv", "direct", "COMMITTED ONLY", "Produced by the authors' script", "no", "-"),
 R("C46", "Cleaned sample 12.8; size/architecture 12.6; config-consistent 13.5; cap-15 14.6; MMLU-Redux 13.4/13.3", "V-E", "statistical", "Table V", "tab_robust.tex", "direct", "COMMITTED ONLY", "Cleaned sample reproduced independently (12.78); the rest committed only", "no", "-"),
 R("C47", "Config-file check: 191 models, 142 reach the declared root, 48 another root, 1 none", "V-E", "descriptive", "config_check", "results/exp04_revision2/info.json", "direct", "COMMITTED ONLY", "-", "no", "-"),
 R("C48", "Tree-distance gradient 18.5 / 13.6 / 11.5; within roots +5.5 and +2.3", "V-F; S6", "statistical", "R2, R8", "revision2.csv; R8.csv", "direct", "COMMITTED ONLY", "Within-root fit not recomputed", "no", "-"),
 R("C49", "Leave-one-root-out range 13.1-14.4; unweighted per-root mean 25.3; DL pooled 16.6 (12.5-20.8), tau 7.9", "V-G", "statistical", "independent", "independent_checks.json", "direct", "REPRODUCED", "13.10-14.36; 25.3; 16.6 [12.5, 20.8]; 7.9", "no", "-"),
 R("C50", "Capability bands (13.3 above 0.60; 11.6 at 0.50-0.60) and subjects (all 57 positive, median 12.2, range 7.0-18.0; same-month median +0.6, 13 intervals exclude 0)", "V-G", "statistical", "heterogeneity outputs", "results/exp04_heterogeneity", "direct", "COMMITTED ONLY", "-", "no", "-"),
 R("C51", "13 points is a 31% increase over the mean", "VI", "arithmetic", "13.3/42.3", "-", "direct", "VERIFIED", "31.4%", "no", "-"),
 R("C52", "'Why lineage and not release timing': three post-hoc features fit the lineage reading; hypotheses, not mechanisms", "VI", "interpretive", "-", "-", "indirect", "AUTHOR STATEMENT", "Heading reads as a conclusion; text is appropriately hedged; pretraining era is nested in lineage", "mild", "Retitle 'Why lineage may matter more than release timing' (ISS-07)"),
 R("C53", "Implications: related models' agreement over-counts as independent confirmation; ensemble benefit untested", "VI", "interpretive", "-", "-", "indirect", "AUTHOR STATEMENT", "Explicitly marked as untested hypothesis", "no", "-"),
 R("C54", "Limitations: only 1 same-root pair at >=12 months; no single root moves the estimate by >1.1; 339/977 and 247/590 below 0.30", "VII", "descriptive", "independent", "independent_checks.json", "direct", "REPRODUCED", "1 pair; 13.10-14.36; 339 / 247", "no", "-"),
 R("C55", "README commands rebuild every table from committed outputs and, after re-download, every analysis and figure", "Data Availability", "reproducibility", "clean-checkout run", "audit/outputs/repro_log.txt", "direct", "VERIFIED", "Tables byte-identical; PDFs rebuild; 14/20 figures from committed outputs; metadata->roster->frozen-hash chain reproduced today; full 977-file re-download NOT repeated (last by authors on 9 Oct)", "no", "State the 6 figures that need the re-download (done in README)"),
 R("C56", "Per-item files and metadata declare no licence, so answer files and three metadata fields are not redistributed", "Data Availability", "reproducibility", "repository state", ".gitignore; frozen/", "direct", "VERIFIED", "datasets/ollb/v1 and frozen_full are ignored; compact frozen lists omit three fields", "no", "-"),
 R("C57", "Related work descriptions (Kim; Goel; Chen; Kuai; D. Kim; Bugaud; Li & Hai; Hossain; Tieman; Jo; Paquin; Laufer; Tamura; Choi; Nikolic; PhyloLM; Horwitz; Wu; Li; Messing; Gema)", "II; Table I", "literature", "original sources", "arXiv, PMLR, ACL Anthology, ICLR, NeurIPS pages", "direct", "VERIFIED", "All attributed claims found in the sources; Li & Hai: 20 open-weight models / 10 families, same-family interval includes zero; Hossain: 'suggestive', 4 models; Kuai: 18 LLMs, 6 families", "no", "-"),
 R("C58", "First study to examine declared ancestry and release proximity jointly as correlates of agreement on wrong answers", "II", "novelty", "literature search", "-", "indirect", "AUTHOR STATEMENT", "Hedged ('to our knowledge'); no counterexample among the verified sources", "mild", "Keep hedge"),
 R("C59", "AI disclosure names the system, sections and level of use, in the Acknowledgment", "Acknowledgment", "integrity", "IEEE policy", "IEEE Author Center policy page", "direct", "VERIFIED", "Complies with the policy; accuracy of the described use is an author statement consistent with git trailers", "no", "Authors to confirm (ISS-14)"),
 R("C60", "S7: all 16 saved per-question files predict option A on all 14,042 items with one log-likelihood per item; Qwen-7B accuracy equals the all-A share", "S7", "descriptive", "the files", "datasets/eval_samples; phase2_eval_results.csv", "direct", "REPRODUCED", "16/16 files; 3222/14042 = 0.2295", "no", "-"),
 R("C61", "S1: per-model variance decomposition needs ~60 families and 14 quarters for RMSE <=0.10", "IV-A; S1", "statistical", "Monte Carlo", "results/precision_gate", "direct", "COMMITTED ONLY", "Not re-run", "no", "-"),
 R("C62", "S5: agreement separates same-root from different-root pairs (AUC 0.95; 0.88 adjusted); 68% vs 2.1% above 0.7", "S5", "descriptive", "heterogeneity info", "info.json", "direct", "COMMITTED ONLY", "AUCs re-derived by the figure script (assert); not independent", "no", "-"),
]

issues = [
 ["ISS-01", "minor", "paper/src/ieee_access_manuscript.tex III-C ('frozen ... before any prediction was downloaded')", "Reference-model answer file written 11:39 IST (mtime) and first log records; freeze commit 3cb6308 at 13:15; bulk download from 13:46", "Overstates the chronology by one file; no effect on any estimate (the reference model did not influence roster or cap)", "Reword to 'before the bulk download; only the reference model, needed for the answer key, had been fetched earlier'", "grep the sentence; no other claim changes", "Open"],
 ["ISS-02", "minor", "III-A, spot check", "Llama-2-7b-hf npz accuracy 42.76% (micro, item-level); 43.80% is the 57-subject macro-average (computed 43.80)", "Reader comparing the paper's own accuracy (0.4276) with 43.80 sees a mismatch", "'its accuracy averaged over the 57 subjects, as the leaderboard reports it, is 43.80 (item-level 42.76)'", "recompute both averages", "Open"],
 ["ISS-03", "minor", "Abstract; III-C", "590 primary entries = 552 distinct prediction vectors = 563 distinct Hub repositories; 4 case-variant pairs are one Hub repository", "'590 models' slightly overstates independent units; effect bounded (cleaned sample 12.78 vs 13.29)", "Say 'leaderboard entries' where the count is introduced and keep the Data Quality paragraph", "grep", "Open"],
 ["ISS-04", "moderate", "Abstract; IV-E; V-E", "Jackknife variance: one root accounts for 68.6% (top 5: 86.4%) of the squared leave-one-out deviations; root bootstrap CI [11.5, 19.0] is asymmetric; dropping both largest roots gives 15.95 [12.8, 19.1]", "Normal-approximation CI rests on few influential clusters; a reviewer will ask", "Report the bootstrap interval beside the headline CI and add the drop-top-2 estimate (strengthens the result)", "independent_checks.json", "Open"],
 ["ISS-05", "moderate", "VI; Table III ('same-root-organisation predictor: Not done')", "Audit sensitivity: same-uploader pairs agree +6.75 more; shared-root stays 12.93 (jackknife SE 1.09) controlling for it; only 140 of 2,020 same-root pairs share an uploader", "Obvious reviewer confound (developer recipes) is addressable with a result already in hand", "Add as a post-hoc robustness row (S6); update Table III", "audit/outputs/uploader_check.json", "Open (optional strengthening)"],
 ["ISS-06", "minor", "V-G / S6", "Unweighted mean of per-root coefficients (25.3) averages 63 roots of which 46 have <10 same-root pairs (77 pairs total, mean coefficient 28.1)", "The 25.3 'counting each root once' is dominated by very noisy tiny roots; 16.6 (precision weighted) is the better summary", "Add one clause: 46 of the 63 roots contribute fewer than 10 pairs each", "independent_checks.json", "Open"],
 ["ISS-07", "minor", "VI heading 'Why lineage and not release timing'", "Section is hedged but the heading states a conclusion; pretraining era is nested in lineage (acknowledged in VII)", "Overstates relative to design", "'Why lineage may matter more than release timing'", "grep", "Open"],
 ["ISS-08", "minor", "V-C, V-D ('within 0.6 points of zero in both populations')", "True for the pre-specified baseline; S1 gives +1.0 and +1.4", "Ambiguous scope", "'in the pre-specified model'", "table check", "Open"],
 ["ISS-09", "minor", "V-D 'Neither measure alone shows a positive association'", "Same paragraph lists positive specifications", "Internal tension", "'... in the pre-specified model'", "grep", "Open"],
 ["ISS-10", "minor", "IV-F ('an hour before')", "Plan commit 11:27:33, OLS specification commit 12:06:33 = 39 min", "Imprecise", "'about forty minutes'", "git log", "Open"],
 ["ISS-11", "minor", "III-A and later: 'MMLU', 'CI'", "Abbreviations defined only in the abstract (IEEE Access requires definition at first use in the body)", "Template compliance", "Expand MMLU at first body use; expand 'confidence interval (CI)'", "regex scan", "Open"],
 ["ISS-12", "moderate", "src/lineage_era/ollb/analysis.py load_population/choice_matrix; results/exp04_validation/per_model.csv", "Manifest stores accuracy but no content hash; loader never compares them. Reproducer audit/tools/repro_gate_limit.py: swapping two validated models' files passes every gate check", "A mis-assigned or stale file could enter silently; not occurring now (977/977 accuracies match)", "Compare file accuracy to manifest accuracy (or add sha256 to the manifest) and fail on mismatch; add a test", "run repro_gate_limit.py -> must raise", "Open"],
 ["ISS-13", "moderate", "tests (src/lineage_era/test_*.py)", "ollb package coverage 16% (fetch_v1, roster, roster_v1, config_lineage, hub_meta 0%); no unit test for the jackknife, validation_report, or the headline pipeline", "Statistical core verified only by this audit's independent code", "Promote audit/tools/independent_verify.py checks into tests (small synthetic population)", "pytest --cov", "Open"],
 ["ISS-14", "minor", "Acknowledgment; IEEE Access policy", "Policy asks disclosure in Acknowledgment naming system, sections and level (met); submission guidance also asks AI-generated sections to cite the system; citation [38] appears only in the Acknowledgment", "Possible editorial query", "Confirm with the editorial office whether a first-use citation in the drafted sections is expected; authors to confirm the stated level of use", "policy pages", "Open (author action)"],
 ["ISS-15", "minor", "Author biographies; first page", "Two biographies say 'received the degree' with no degree; DOI/date/volume are template placeholders; ORCID required for submitting author", "IEEE requires complete biographies for all authors", "Authors supply degrees (photos optional per page); publisher fills placeholders", "visual", "Open (author action)"],
 ["ISS-16", "minor", "datasets/eval_samples/, datasets/phase2_eval_results.csv, results/phase2_empirical/", "Invalid earlier-evaluation data have no in-folder notice (docs have banners)", "Could be mistaken for valid data", "Add an INVALID_DO_NOT_USE.md in each folder", "ls", "Open"],
 ["ISS-17", "minor", "docs/REPRODUCIBILITY_CHECKLIST.md; README", "The only script that implements the seed-0 cap-40 sampling (scripts/compare_rosters.py) is not named in the runbook", "Reproducer must discover it", "Add it as a step before download_ollb_v1.py", "grep", "Open"],
 ["ISS-18", "minor", "requirements.txt; pyproject.toml", "Core packages pinned; huggingface_hub, pyarrow, tabulate, pytest unpinned; no lockfile", "Data-retrieval path not version-locked", "Pin or add a lock file", "pip freeze diff", "Open"],
 ["ISS-19", "minor", "scripts/make_exp04_figures.py: fig_raw_adjusted; paper/figures; supplement figs fig_item_null, fig_gate_audit", "Text below 7 pt: main Fig. 8 exponent digits 5.6 pt; supplement fig_item_null 5.3 pt, fig_gate_audit 5.1-6.8 pt at placed size; main-paper minimum otherwise 7.4 pt", "Readability at print size", "Use plain tick labels in Fig. 8; enlarge the two supplement figures", "pymupdf font sizes (audit/outputs/figure_sizes.csv)", "Open"],
 ["ISS-20", "minor", "src/lineage_era/ollb/analysis.py (float32 matmul)", "numpy RuntimeWarnings (divide by zero / overflow / invalid in matmul) printed on macOS Accelerate; results identical to float64 independent code", "Alarming but harmless output", "Use float64 or suppress with a comment", "run analysis", "Open"],
 ["ISS-21", "info", "datasets/ollb/v1 on case-insensitive filesystems", "973 files for 977 models: 4 case-variant pairs (e.g. Facebook/OPT-125M, facebook/opt-125m) are the same Hub repository (identical run ids)", "Confuses a file count", "Note in README", "ls | wc", "Open"],
 ["ISS-22", "info", "Git hygiene", "Local main is 72 commits behind origin; stash@{0} unrelated; backup/pre-history-rewrite local only; history was rewritten once (hashes changed, dates preserved 26/26)", "None for the paper", "Fast-forward main; keep backup tag", "git status", "Open"],
 ["ISS-23", "moderate", "Reproducibility claim", "Full 977-file re-download and validation not repeated in this audit (3 models re-extracted; metadata, roster, frozen hashes, sampling reproduced)", "Last full test 9 Oct (authors)", "Rerun scripts/download_ollb_v1.py in a clean environment before submission and record the exit code", "download + validation_report exit 0", "Open"],
]

with open(A / "CLAIM_EVIDENCE_LEDGER.csv", "w", newline="") as f:
    w = csv.writer(f); w.writerow(H); w.writerows(ledger)
with open(A / "ISSUE_REGISTER.csv", "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["id", "severity", "file_and_location", "evidence", "impact", "required_action", "verification_test", "status"])
    w.writerows(issues)
from collections import Counter
print(len(ledger), "claims:", dict(Counter(r[7] for r in ledger)))
print(len(issues), "issues:", dict(Counter(r[1] for r in issues)))
